const SITE="https://baletisauvage.github.io";
const COOKIE="baleti_admin", SESSION=43200, MAX_FAIL=5, WINDOW=900;
const DEFAULTS={mode:"thu",usualPlace:"Place des Martyrs de la Résistance",usualLat:43.6108225,usualLng:3.8766489,baletiText:"Le texte de présentation du Balèti Sauvage sera affiché ici."};
const headers=(extra={})=>({"Access-Control-Allow-Origin":SITE,"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Credentials":"true",...extra});
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:headers({"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...extra})});
function safe(a,b){a=String(a||"");b=String(b||"");if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0}
async function hash(s){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function signature(p){return hash("Baleti Sauvage administration|"+p)}
async function auth(req,env){if(!env.ADMIN_PASSWORD)return false;const m=(req.headers.get("Cookie")||"").match(/(?:^|;\s*)baleti_admin=([^;]+)/);return !!m&&safe(m[1],await signature(env.ADMIN_PASSWORD))}
async function rateTable(env){await env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_login_rate (key TEXT PRIMARY KEY, failures INTEGER NOT NULL DEFAULT 0, first_failure INTEGER NOT NULL, last_failure INTEGER NOT NULL)").run()}
async function rateKey(req,env){return hash(`baleti-login|${req.headers.get("CF-Connecting-IP")||"unknown"}|${env.ADMIN_PASSWORD||""}`)}
async function blocked(env,key){await rateTable(env);const now=Math.floor(Date.now()/1000),r=await env.DB.prepare("SELECT failures,first_failure FROM admin_login_rate WHERE key=?").bind(key).first();if(!r)return false;if(now-Number(r.first_failure)>=WINDOW){await env.DB.prepare("DELETE FROM admin_login_rate WHERE key=?").bind(key).run();return false}return Number(r.failures)>=MAX_FAIL}
async function fail(env,key){await rateTable(env);const now=Math.floor(Date.now()/1000),r=await env.DB.prepare("SELECT failures,first_failure FROM admin_login_rate WHERE key=?").bind(key).first();if(!r||now-Number(r.first_failure)>=WINDOW){await env.DB.prepare("INSERT OR REPLACE INTO admin_login_rate(key,failures,first_failure,last_failure) VALUES(?,1,?,?)").bind(key,now,now).run()}else await env.DB.prepare("UPDATE admin_login_rate SET failures=failures+1,last_failure=? WHERE key=?").bind(now,key).run()}
async function settings(DB){const {results}=await DB.prepare("SELECT key,value FROM settings").all(),s={...DEFAULTS};for(const r of results||[]){try{s[r.key]=JSON.parse(r.value)}catch{s[r.key]=r.value}}return s}
async function save(DB,key,value){await DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(key,JSON.stringify(value)).run()}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:headers()});try{const u=new URL(request.url),p=u.pathname;
if(p==="/")return json({ok:true,site:"Balèti Sauvage Montpellier",worker:"connecté",database:!!env.DB,adminConfigured:!!env.ADMIN_PASSWORD});
if(p==="/api/public"&&request.method==="GET"){const links=await env.DB.prepare("SELECT id,title,url,position FROM links ORDER BY position,id").all();return json({ok:true,settings:await settings(env.DB),links:links.results||[]})}
if(p==="/api/login"&&request.method==="POST"){const body=await request.json(),key=await rateKey(request,env);if(await blocked(env,key))return json({ok:false,error:"Trop de tentatives. Réessaie dans quelques minutes."},429);if(!env.ADMIN_PASSWORD||!safe(body.password,env.ADMIN_PASSWORD)){await fail(env,key);return json({ok:false,error:"Mot de passe incorrect"},401)}await env.DB.prepare("DELETE FROM admin_login_rate WHERE key=?").bind(key).run();return json({ok:true},200,{"Set-Cookie":`${COOKIE}=${await signature(env.ADMIN_PASSWORD)}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=${SESSION}`})}
if(p==="/api/session"&&request.method==="GET")return json({ok:true,authenticated:await auth(request,env)});
if(p==="/api/logout"&&request.method==="POST")return json({ok:true},200,{"Set-Cookie":`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=0`});
if(!(await auth(request,env)))return json({ok:false,error:"Non autorisé"},401);
if(p==="/api/settings"&&request.method==="POST"){const b=await request.json(),allowed=["mode","usualPlace","usualLat","usualLng","baletiText"];if(!allowed.includes(b.key))return json({ok:false,error:"Réglage non autorisé"},400);await save(env.DB,b.key,b.value);return json({ok:true})}
return json({ok:false,error:"Route inconnue"},404)}catch(e){return json({ok:false,error:"Erreur Worker",detail:String(e?.message||e)},500)}}};
